# Generated by Django 2.1.7 on 2019-03-28 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='original_release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 2, 3, 24, 150637, tzinfo=utc), verbose_name='original release date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='watchers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producturl',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_monitor.Product'),
        ),
    ]
